JAD-2146 added dataset attach functionality
JADBio/JADBioPythonClient pull request #13
Opened 2022-03-01 15:36 UTC by sfafalios

2022-03-01 15:50 UTC, p01K submitted a review, later dismissed

2022-03-01 16:16 UTC, borbudak-jadbio requested changes

2022-03-01 16:16 UTC, borbudak-jadbio commented on jadbio/client.py
> +        :param str project_id: The destination project were the specified dataset will be attached to. The user should
```suggestion
        :param str project_id: The destination project where the specified dataset will be attached to. The user should
```

2022-03-01 16:16 UTC, borbudak-jadbio commented on jadbio/client.py
> +
Please add a one-line description of the method

2022-03-08 16:57 UTC, borbudak-jadbio approved these changes

2022-03-08 18:43 UTC, merged